### ISSUE TITLE
Error Contents: No module named 'PIL'

### ISSUE THREAD

**Issue by chicken4rice** [zim514/script.service.hue#178]
Got this snippet from the Kodi Logs:  
Cant figure out why it cant find PIL.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'PIL'
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi19L/.kodi/addons/script.service.hue/service.py", line 8, in <module>
                                                       from resources.lib import core, reporting
                                                     File "/opt/Kodi19L/.kodi/addons/script.service.hue/resources/lib/core.py", line 12, in <module>
                                                       from resources.lib import ambigroup, lightgroup
                                                     File "/opt/Kodi19L/.kodi/addons/script.service.hue/resources/lib/ambigroup.py", line 12, in <module>
                                                       from PIL import Image
                                                   ModuleNotFoundError: No module named 'PIL'
                                                   -->End of Python script error report<--
                                                   
DEBUG <general>: onExecutionDone(13, /opt/Kodi19L/.kodi/addons/script.service.hue/service.py)

**Comment by chicken4rice** [comment]
turns out only the python2 version of pillow was being installed via kodi, had to manually remove it and then update pip3 in order to install pillow for python3
