### ISSUE TITLE
JSONDecodeError: [Errno Expecting value] : 0

### ISSUE THREAD

**Issue by zim514** [zim514/script.service.hue#220]
View details in Rollbar: [https://rollbar.com/krisyoung/script.service.hue/items/506/](https://rollbar.com/krisyoung/script.service.hue/items/506/)

```
Traceback (most recent call last):
  File "/storage/.kodi/addons/script.service.hue/service.py", line 9, in <module>
    core.core() #Run Hue service
  File "/storage/.kodi/addons/script.service.hue/resources/lib/core.py", line 30, in core
    commands(monitor, command)
  File "/storage/.kodi/addons/script.service.hue/resources/lib/core.py", line 38, in commands
    bridge_discovered = kodiHue.bridgeDiscover(monitor)
  File "/storage/.kodi/addons/script.service.hue/resources/lib/kodiHue.py", line 122, in bridgeDiscover
    bridgeIP = _discoverNupnp()
  File "/storage/.kodi/addons/script.service.hue/resources/lib/kodiHue.py", line 79, in _discoverNupnp
    res = req.json()
  File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
JSONDecodeError: [Errno Expecting value] : 0Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
  File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
  File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
  File "/usr/lib/python3.8/site-packages/simplejson/scanner.py", line 79, in scan_once
  File "/usr/lib/python3.8/site-packages/simplejson/scanner.py", line 39, in _scan_once
JSONDecodeError: Expecting value: line 1 column 1 (char 0)Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/simplejson/scanner.py", line 37, in _scan_once
IndexError: string index out of range
```

**Comment by zim514** [comment]
Occuring on ancient version. WNF
