### ISSUE TITLE
RuntimeError: Kodi is not playing any videofile

### ISSUE THREAD

**Issue by zim514** [zim514/script.service.hue#249]
View details in Rollbar: [https://rollbar.com/krisyoung/script.service.hue/items/528/](https://rollbar.com/krisyoung/script.service.hue/items/528/)

```
Traceback (most recent call last):
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\service.py", line 11, in <module>
    core.core()
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\resources\lib\core.py", line 25, in core
    _commands(monitor, command)
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\resources\lib\core.py", line 38, in _commands
    _service(monitor)
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\resources\lib\core.py", line 147, in _service
    activate(light_groups)
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\resources\lib\core.py", line 205, in activate
    g.activate()
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\resources\lib\lightgroup.py", line 140, in activate
    self.onAVStarted()
  File "D:\Kodi Media Center\portable_data\addons\script.service.hue\resources\lib\ambigroup.py", line 91, in onAVStarted
    self.video_info_tag = self.getVideoInfoTag()
RuntimeError: Kodi is not playing any videofile
```

**Comment by zim514** [comment]
_Not sure if this can be fixed, but when the lights power on by schedule (Sunset), if playing a PVR channel that only contains audio and no video stream (Radio), the Hue add-on generates an on-screen Error dialog that 'No Video is currently Playing', which is true, because i'm playing a radio channel, not a video channel, at that point in time._

https://forum.kodi.tv/showthread.php?tid=344886&pid=3152255#pid3152255
