### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by heitbaum** [zim514/script.service.hue#250]
**Describe the bug**
- Experiencing issue #181 with version 1.4.15

```

2023-05-19 20:00:09.554 T:150213    info <CWebserver[8080]>: Skipped 1 duplicate messages..
2023-05-19 20:00:09.554 T:150213   debug <CWebserver[8080]>: request received for /jsonrpc
2023-05-19 20:00:09.571 T:2742  warning <general>: RunScript called for a non-script addon 'script.service.hue'. This behaviour is deprecated.
2023-05-19 20:00:09.571 T:150232   debug <general>: Thread LanguageInvoker start, auto delete: false
2023-05-19 20:00:09.571 T:150232   debug <general>: initializing python engine.
2023-05-19 20:00:09.571 T:150232   debug <general>: CPythonInvoker(27, /storage/.kodi/addons/script.service.hue/service.py): start processing
2023-05-19 20:00:09.582 T:150232   debug <general>: -->Python Interpreter Initialized<--
2023-05-19 20:00:09.582 T:150232   debug <general>: 
                                                   
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27, /storage/.kodi/addons/script.service.hue/service.py): the source file to load is "/storage/.kodi/addons/script.service.hue/service.py"
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27): full python path:
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):   custom python path:
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.certifi/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.chardet/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.idna/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.pyrollbar/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.qhue/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.requests/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.six/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.module.urllib3/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /storage/.kodi/addons/script.service.hue
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /usr/share/kodi/addons/script.module.pil/lib
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):   default python path:
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /usr/lib/python311.zip
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /usr/lib/python3.11
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /usr/lib/python3.11/lib-dynload
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):     /usr/lib/python3.11/site-packages
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27): adding args:
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):  service.py
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27):  discover
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27, /storage/.kodi/addons/script.service.hue/service.py): entering source directory /storage/.kodi/addons/script.service.hue
2023-05-19 20:00:09.582 T:150232   debug <general>: CPythonInvoker(27, /storage/.kodi/addons/script.service.hue/service.py): instantiating addon using automatically obtained id of "script.service.hue" dependent on version 3.0.0 of the xbmc.python api
2023-05-19 20:00:09.659 T:150232   debug <general>: [script.service.hue] Validate schedule. Schedule Enabled: False
2023-05-19 20:00:09.659 T:150232   debug <general>: [script.service.hue] Validate ambilight config. Enabled: False
2023-05-19 20:00:09.659 T:150232   debug <general>: [script.service.hue] Started with discover
2023-05-19 20:00:09.659 T:150232   debug <general>: [script.service.hue] Start discover
2023-05-19 20:00:09.661 T:150232   debug <general>: DialogProgress::Open called 
2023-05-19 20:00:09.669 T:2742    debug <general>: ------ Window Init (DialogConfirm.xml) ------
2023-05-19 20:00:09.670 T:150232   debug <general>: [script.service.hue] In kodiHue discover_nupnp()
2023-05-19 20:00:09.812 T:2742    debug <general>: ------ Window Deinit (DialogAddonSettings.xml) ------
2023-05-19 20:00:12.947 T:150232   debug <general>: [script.service.hue][EXCEPTION] Service exception: Expecting value: line 1 column 1 (char 0)
2023-05-19 20:00:12.949 T:150232   debug <general>: [script.service.hue] Exception: <class 'simplejson.errors.JSONDecodeError'>, Expecting value: line 1 column 1 (char 0), , Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.service.hue/service.py", line 11, in <module>
                                                       core.core()
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/core.py", line 25, in core
                                                       _commands(monitor, command)
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/core.py", line 34, in _commands
                                                       hue_connection = hueconnection.HueConnection(monitor, silent=True, discover=True)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/hueconnection.py", line 31, in __init__
                                                       self.discover()
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/hueconnection.py", line 118, in discover
                                                       bridge_ip_found = self._discover_nupnp()
                                                                         ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/hueconnection.py", line 196, in _discover_nupnp
                                                       result = req.json()
                                                                ^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
2023-05-19 20:00:12.950 T:2742    debug <general>: ------ Window Init (DialogConfirm.xml) ------




2023-05-19 20:00:18.063 T:150213   debug <CWebserver[8080]>: request received for /jsonrpc
2023-05-19 20:00:20.213 T:2742     info <general>: Skipped 2 duplicate messages..
2023-05-19 20:00:20.213 T:2742    debug <general>: ------ Window Deinit (DialogConfirm.xml) ------
2023-05-19 20:00:20.250 T:150232   debug <general>: CPythonInvoker(27, /storage/.kodi/addons/script.service.hue/service.py): script successfully run
2023-05-19 20:00:20.250 T:150232    info <general>: CPythonInvoker(27, /storage/.kodi/addons/script.service.hue/service.py): waiting on thread 139739554367168
2023-05-19 20:00:20.493 T:2742    debug <general>: ------ Window Deinit (DialogConfirm.xml) ------
2023-05-19 20:00:23.654 T:150232   debug <general>: onExecutionDone(27, /storage/.kodi/addons/script.service.hue/service.py)
2023-05-19 20:00:23.663 T:150232   debug <general>: .
2023-05-19 20:00:23.680 T:150232    info <general>: Skipped 1 duplicate messages..
2023-05-19 20:00:23.680 T:150232   debug <general>: Python interpreter stopped
2023-05-19 20:00:23.680 T:150232   debug <general>: Thread LanguageInvoker 139738505803456 terminating
```

**To Reproduce**
1. Choose `Discover Hue Bridge / Enter IP
2. `N-UPnP discovery…` dialog comes up
3. The following error occurred: Expecting value: line 1 column 1 (char 0)
4. Automatically report this error?
5. Chose “Yes”

**Expected behavior**
Successful discovery

**Screenshots**
Na

**System (please complete the following information):**
 - OS: [e.g. Windows, Linux, LibreElec, Android] LibreELEC 12 master
 - System Version [e.g. 10] 12
 - Kodi Version [e.g. 19] 21

**Additional context**
NA

**Comment by heitbaum** [comment]
Issue seems to be: https://www.reddit.com/r/Hue/comments/wxi9wf/discoverymeethuecom_429_error/

nuc12:~/.kodi/addons/script.service.hue/resources/lib # wget https://discovery.meethue.com/
Connecting to discovery.meethue.com (34.117.13.189:443)
wget: server returned error: HTTP/1.1 429 Too Many Requests

is it possible to use avahi?

```
# avahi-browse -d local _hue._tcp --resolve -t
+   eth0 IPv6 Philips Hue - xxxxxx                          _hue._tcp            local
+   eth0 IPv4 Philips Hue - xxxxxx                          _hue._tcp            local
=   eth0 IPv4 Philips Hue - xxxxxx                          _hue._tcp            local
   hostname = [Kitchen.local]
   address = [192.168.xx.41]
   port = [443]
   txt = ["modelid=BSB002" "bridgeid=001788fffexxxxxx"]
=   eth0 IPv6 Philips Hue - xxxxxx                          _hue._tcp            local
   hostname = [Kitchen.local]
   address = [192.168.xx.41]
   port = [443]
   txt = ["modelid=BSB002" "bridgeid=001788fffexxxxxx"]
```
