### ISSUE TITLE
Error in logs (2.0.12) of info_tag.getDuration

### ISSUE THREAD

**Issue by heitbaum** [zim514/script.service.hue#302]
**Describe the bug**
- Error in logs (2.0.12) of info_tag.getDuration
- See log snipit below 

**To Reproduce**
1. On playback I have a hue action to dim the lights

**Expected behavior**
No log error

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows, Linux, LibreElec, Android] LibreElec
 - System Version [e.g. 10] 13 master (Python 3.12.7)
 - Kodi Version [e.g. 19] Starting Kodi (22.0-ALPHA1 (21.90.700) Git:32b04718c65a90f87e409674c4ef984b087b8657). Platform: Linux x86 64-bit

**Additional context**
```
2024-10-28 21:46:34.863 T:3170    debug <general>: [SCRIPT.SERVICE.HUE] LightGroup[0] onPlaybackStarted. Group enabled: True, Bridge connected: True, mediaType: 0
2024-10-28 21:46:34.863 T:3170    debug <general>: [SCRIPT.SERVICE.HUE] LightGroup[0] onPlaybackStarted. play_behavior: False, media_type: 0 == playback_type: 0
2024-10-28 21:46:34.863 T:3170    debug <general>: [SCRIPT.SERVICE.HUE] Validate Activation LightGroup[0] Scene: -1, media_type: 0, skip_time_check_if_light_on: False, skip_scene_if_all_off: False
2024-10-28 21:46:34.863 T:3170    debug <general>: [SCRIPT.SERVICE.HUE] _is_within_schedule: True, Schedule not enabled
2024-10-28 21:46:34.866 T:3170    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'getDuration'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/lightgroup.py", line 66, in onAVStarted
                                                       if self.activation_check.validate(play_scene):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/lightgroup.py", line 320, in validate
                                                       elif self._is_within_schedule() and self._video_activation_rules():
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.service.hue/resources/lib/lightgroup.py", line 202, in _video_activation_rules
                                                       duration = info_tag.getDuration() / 60
                                                                  ^^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'getDuration'
                                                   -->End of Python script error report<--
                                                   
2024-10-28 21:46:34.867 T:3170    debug <general>: [SCRIPT.SERVICE.HUE] LightGroup[1] onPlaybackStarted. Group enabled: False, Bridge connected: True, mediaType: 1
```

**Comment by zim514** [comment]
I'm not sure what's going on, can you please include more logs from earlier? It looks like you may not have a scene configured for video playback. I have some of these in the crash reporting as well that I can't track down but it looks like many of them might be on Xbox / Windows App store version, is that the case for you?

**Comment by heitbaum** [comment]
> I'm not sure what's going on, can you please include more logs from earlier? It looks like you may not have a scene configured for video playback. I have some of these in the crash reporting as well that I can't track down but it looks like many of them might be on Xbox / Windows App store version, is that the case for you?

Mine is on LibreELEC master. I can reproduce it every time. I’ll try to get some more details for you.

**Comment by zim514** [comment]
It should be addressed in latest, can you give it a shot?

**Comment by heitbaum** [comment]
> It should be addressed in latest, can you give it a shot?

Yes that fixed it.

**Comment by zim514** [comment]
Thanks for confirming!
